### ISSUE TITLE
DS2430A write fails

### ISSUE THREAD

**Issue by mjm2017** [pceric/DallasEPROM#2]
Hi, 
Thank you for this great library. 

I have a problem regarding writing on the mentioned device. Looking at the datasheet, it says that you should send a command byte which I cannot find it in your code. Bellow is from the datasheet. 

> COPY SCRATCHPAD [55h]
After  the  data  stored  in  the  scratchpad  has  been  verified  the  master  may  send  the  Copy  Scratchpad  command  followed  by  a  validation  key  of  **A5h**  to  transfer  data  from  the  scratchpad  to  the  EEPROM memory.  This  command  always  copies  the  data  of  the  entire scratchpad. > 
I get error code -5
And when I write the 32 bytes, the last byte get zero al the time .. I send 0x02. 
Do you have any suggestion?

**Comment by pceric** [comment]
After looking through the datasheets I see that the DS2430 has a slightly different write procedure than the DS2431 and DS2433.  I only have the 33 on hand to test with at the moment. You could probably get it to work by replacing the 3 byte dynamic auth with the 1 byte static auth found on the 30.  I think everything else would be the same.

**Comment by pceric** [comment]
I just committed a fix that might allow the DS2430 to work.  I don't have any way to confirm however.
