### ISSUE TITLE
Fixed but please how can I send you the changes?

### ISSUE THREAD

**Issue by MariwanJ** [pceric/DallasEPROM#4]
Hi, 
Still I couldn't get it works. 
I made several changes and added several function were missing .. Please let me know how I can send you the changes?
Ok, I send the files using this forum. Please take care of the changes.
Regards, 
Mariwan

[DallasEPROM-master.zip](https://github.com/pceric/DallasEPROM/files/1208130/DallasEPROM-master.zip)

**Comment by pceric** [comment]
You can submit changes using GitHub's pull request feature.

From your changes I see another problem, the DS2430 has 1 byte addresses but all other chips have 2 byte addresses.  I've made some more changes and have them in the "test" branch.  You can test using that branch and see if it works now.

**Comment by MariwanJ** [comment]
Thanks for your reply. Since I use Windows, GIT is not as easy as in Linux. I will try to send it in that way also.
But, please look carefully to the changes I made. I added several functions that you don't provide for any device. These functions are for writing and reading the APPLICATION REGISTER.
You need to add them to the code. 
I might need some time to send you the changes via git .. Otherwise you have a working code for the DS2430 I uploaded to you with in this page. 
Best Regards, and thanks for everything.
Mariwan Jalal

**Comment by pceric** [comment]
Additional code was added and merged for DS2430 for application register support hopefully without braking any other chip.  Submit another bug and/or pull request if you have issues.
